{% set name = "pyleiden" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyleiden-{{ version }}.tar.gz
  sha256: 61d9fa1b8a71b1f13bebc6b94e6eed2f6d4a1228ac223dab03db67f77ff3ae49

build:
  entry_points:
    - pyleiden = pyleiden.pyleiden:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.6
    - python-igraph >=0.10.3

test:
  imports:
    - pyleiden
  commands:
    - pip check
    - pyleiden --help
  requires:
    - pip

about:
  summary: 'pyLeiden: a CLI tool for clustering with the Leiden algorithm'
  home: https://github.com/apcamargo/pyleiden
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apcamargo
